id: mysql-default-login

info:
  name: MySQL - Default Login
  author: DhiyaneshDk,pussycat0x,ritikchaddha
  severity: high
  description: |
    A MySQL service was accessed with easily guessed credentials.
  metadata:
    verified: true
    max-request: 21
    shodan-query: "port:3306"
  tags: js,mysql,default-login,network,fuzz,enum

javascript:
  - pre-condition: |
      isPortOpen(Host,Port);
    code: |
      var m = require("nuclei/mysql");
      var c = m.MySQLClient();
      c.Connect(Host,Port,Username,Password)

    args:
      Host: "{{Host}}"
      Port: "3306"
      User: "{{usernames}}"
      Pass: "{{passwords}}"

    payloads:
      usernames:
        - root
        - admin
        - mysql
        - test
      passwords:
        - root
        - admin
        - mysql
        - test
        -
    attack: clusterbomb

    matchers:
      - type: dsl
        dsl:
          - "response == true"
          - "success == true"
        condition: and
# digest: 4a0a0047304502203b16c0831093780883fc023d676c54ec2533d4ac05f2071bea5d68c33ca8b63002210092abea71a11967719f8565e6fc01a8e49569bd807e9cc5b80192f8011c456d0f:922c64590222798bb761d5b6d8e72950