### REQUEST
GET /status.htm HTTP/1.1
Host: 185.99.214.43
User-Agent: Mozilla/5.0

### RESPONSE
HTTP/1.1 200 OK
Server: RTK Web 0.9
Set-Cookie: SessionID=; path=/
Content-Type: text/html
Content-Length: 151

<html><head><meta HTTP-EQUIV="Pragma" CONTENT="no-cache"><script language='javascript'>parent.location="/login.htm"</script></head><body></body></html>
