### REQUEST
GET / HTTP/1.1
Host: 109.232.0.107
User-Agent: Mozilla/5.0
Accept: */*

### RESPONSE
HTTP/1.1 302 Found
Set-Cookie: AIROS_24A43C9C9528=f4c9e702560e7814611435ff348d1ad4; Path=/; Version=1
Location: /cookiechecker?uri=/
Content-Length: 0
Date: Mon, 30 May 2016 03:32:40 GMT
Server: lighttpd/1.4.39

