id: discover-swagger
info:
  name: Public Swagger / OpenAPI - Detect
  author: method-security
  severity: info
  description: Detects public Swagger / OpenAPI documentation and specification endpoints
  metadata:
    method-application-type: API_APPLICATION
    method-module-name: SWAGGER
  tags: discovery,swagger,openapi,api
http:
  - method: GET
    path:
      - "{{BaseURL}}"
      - "{{BaseURL}}/"
      - "{{BaseURL}}/swagger-ui.html"
      - "{{BaseURL}}/swagger/index.html"
      - "{{BaseURL}}/swagger.json"
      - "{{BaseURL}}/swagger.yaml"
      - "{{BaseURL}}/swagger/v1/swagger.json"
      - "{{BaseURL}}/swagger/v1/swagger.yaml"
      - "{{BaseURL}}/api/swagger.json"
      - "{{BaseURL}}/api/swagger.yaml"
      - "{{BaseURL}}/api-docs/swagger.json"
      - "{{BaseURL}}/api-docs/swagger.yaml"
      - "{{BaseURL}}/docs"
      - "{{BaseURL}}/swagger"
    redirects: true
    max-redirects: 5
    stop-at-first-match: true
    matchers:
      - type: regex
        part: header
        regex:
          - "(?i)x-powered-by:\\s*swagger"
          - "(?i)x-generator:\\s*(swagger codegen|openapi generator)"
          - "(?i)server:\\s*swagger"
      - type: word
        part: body
        words:
          - "<div id=\"swagger-ui\">"
          - "<title>Swagger UI</title>"
          - "window.ui = SwaggerUIBundle"
          - "SwaggerUIBundle("
          - "swagger-ui-init.js"
          - "swagger-ui.css"
        case-insensitive: true