types:
  # Request Method Enum
  RequestMethod:
    enum:
      - STANDARD
      - HEADLESS
      - BROWSERBASE
  # Headless Struct
  HeadlessConfig:
    properties:
      pathToBrowser: optional<string>
      minDOMStabalizeTime: integer
  # Browserbase Struct
  BrowserbaseConfig:
    properties:
      proxy: optional<boolean>
      countries: optional<list<string>>
  BrowserbaseSecrets:
    properties:
      token: string
      project: string
