imports:
  http: ../common/http.yml
types:
  # Application Enums
  ApplicationResourceTypeAll:
    enum:
      - ALL
  ApplicationResourceType:
    enum:
      - API_APPLICATION
      - CI_CD_PLATFORM
      - CLOUD_BUCKET
      - CONTENT_MANAGEMENT_SYSTEM
      - HYPERVISOR
      - KUBE
      - VDI_APPLICATION
      - VIRTUAL_COMPUTE
      - WEB_SERVER
  ApplicationResourceConfigType:
    discriminated: false
    union:
      - ApplicationResourceType
      - ApplicationResourceTypeAll
  # Config Struct
  DiscoverApplicationConfig:
    properties:
      targets: list<string>
      resourceType: ApplicationResourceConfigType
      timeout: integer
      threads: integer
      proxy: optional<string>
      verboseLogs: boolean
      globalRateLimit: integer
  # Application Fingerprint Attempt Struct
  ApplicationFingerprintAttempt:
    properties:
      resourceType: ApplicationResourceType
      module: string
      request: http.HttpRequestResponse
      finding: boolean
  ApplicationFingerprintTarget:
    properties:
      target: string
      attempts: list<ApplicationFingerprintAttempt>
  # Report Struct
  DiscoverApplicationResult:
    properties:
      targets: optional<list<ApplicationFingerprintTarget>>
  DiscoverApplicationReport:
    properties:
      config: DiscoverApplicationConfig
      result: DiscoverApplicationResult
      errors: optional<list<string>>
