imports:
  http: ../common/http.yml
types:
  # Application Enums
  ApplicationResourceType:
    enum:
      - ALL
      - API_APPLICATION
      - CLOUD_BUCKET
      - CONTENT_MANAGEMENT_SYSTEM
      - KUBE
      - FRAMEWORK
      - REMOTE_ACCESS
      - WEB_SERVER
  # Application Fingerprints File Struct
  ApplicationFingerprintModule:
    properties:
      name: string
      method: http.HttpMethod
      paths: list<string>
      requestParams: optional<http.HttpRequestParams>
      headerIndicators: optional<map<string, optional<list<string>>>>
      bodyIndicators: optional<list<string>>
  ApplicationResource:
    properties:
      name: ApplicationResourceType
      modules: list<ApplicationFingerprintModule>
  ApplicationFingerprints:
    properties:
      fingerprints: list<ApplicationResource>
  ApplicationFingerprintAttempt:
    properties:
      name: string
      requests: optional<list<http.HttpRequestResponse>>
      finding: boolean
      fingerprints: optional<list<ApplicationFingerprints>>
  ApplicationFingerprintTarget:
    properties:
      target: string
      attempts: list<ApplicationFingerprintAttempt>
  # Config Struct
  DiscoverApplicationConfig:
    properties:
      targets: list<string>
      resourceType: ApplicationResourceType
      modules: optional<list<string>>
      verifyTls: boolean
      timeout: integer
  # Report Struct
  DiscoverApplicationResult:
    properties:
      targets: optional<list<ApplicationFingerprintTarget>>
  DiscoverApplicationReport:
    properties:
      config: DiscoverApplicationConfig
      result: DiscoverApplicationResult
      errors: optional<list<string>>
