id: login-classify

info:
  name: Login Page - Classify
  author: MethodSecurity
  severity: info
  description: Login page was detected.
  tags: webpageclassify

requests:
  - method: GET
    path:
      - "{{BaseURL}}"
    redirects: true
    matchers:
      - type: word
        words:
          - "login"
          - "sign in"
        condition: or
        part: body
        case-insensitive: true