id: graphql-api

info:
  name: Public GraphQL API - Detect
  author: MethodSecurity
  severity: info
  description: Public GraphQL API was detected.
  reference: https://graphql.org/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 59
    shodan-query: 'http.title:"graphql"'
  tags: exposure,api,graphql

http:
  - method: POST
    path:
      - "{{BaseURL}}{{paths}}"
    payloads:
      paths:
        - - "/graphql"

    headers:
      Content-Type: application/json
      Accept: application/json
    body: '{"query":"{ __schema { queryType { name } } }"}'
    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "data"
          - "__schema"
          - "queryType"
          - "errors"
        condition: or

      - type: status
        status:
          - 200
          - 400
          - 401
          - 403
          - 500

    extractors:
      - type: regex
        part: body
        group: 1
        regex:
          - '"version":\s*"([0-9]+\.[0-9]+\.[0-9]+)"'