id: grpc-api

info:
  name: Public gRPC API - Detect
  author: MethodSecurity
  severity: info
  description: Public gRPC API was detected.
  reference: https://grpc.io/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cwe-id: CWE-200
  tags: exposure,api,grpc

http:
  - method: POST
    path:
      - "{{BaseURL}}/grpc.health.v1.Health/Check"
      - "{{BaseURL}}/grpc.health.v1alpha.Health/Check"
      - "{{BaseURL}}/grpc.health.v1beta.Health/Check"
      - "{{BaseURL}}/grpc.reflection.v1alpha.ServerReflectionInfo"
      - "{{BaseURL}}/grpc.reflection.v1alpha.ServerReflectionInfo"
      - "{{BaseURL}}/grpc.reflection.v1.ServerReflectionInfo"
      - "{{BaseURL}}/grpc.reflection.v1beta.ServerReflectionInfo"
      - "{{BaseURL}}/auth.Authentication/Login"
      - "{{BaseURL}}/user.UserService/GetUser"
    headers:
      Content-Type: application/grpc
      Accept: application/grpc
    body: "{}"
    stop-at-first-match: true
    matchers-condition: or
    matchers:
      - name: word-matcher-1
        type: word
        words:
          - "application/grpc"
        part: header
      - name: word-matcher-2
        type: word
        words:
          - "grpc-status"
          - "grpc-message"
        part: header
      - name: status-matcher-1
        type: status
        status:
          - 200
      - name: status-matcher-2
        type: status
        status:
          - 501
    extractors:
      - type: regex
        name: "Status"
        part: response
        group: 1
        regex:
          - "HTTP/1.1 ([0-9]{3})"
