id: k8s-detect

info:
  name: k8s Cluster - Detect
  author: MethodSecurity
  severity: info
  description: Checks common k8s fingerprints to identify a k8s cluster
  reference: https://kubernetes.io/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cwe-id: CWE-200
  tags: exposure,api,k8s

requests:
  - method: GET
    path:
      - "{{BaseURL}}/api"
      - "{{BaseURL}}/livez"
      - "{{BaseURL}}/version"
    matchers:
      - type: word
        words:
          - "Kubernetes-Pf-Flowschema-Uid"
          - "Kubernetes-Pf-Prioritylevel-Uid"
        part: header
        condition: and

    extractors: 
      - type: regex
        name: "Status"
        part: response
        group: 1
        regex:
          - "HTTP/1.1 ([0-9]{3})"