id: swagger-api

info:
  name: Public Swagger API - Detect
  author: MethodSecurity
  severity: info
  description: Public Swagger API was detected.
  reference: https://swagger.io/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 59
    shodan-query: 'http.title:"swagger"'
  tags: exposure,api,swagger

http:
  - method: GET
    path:
      - "{{BaseURL}}{{paths}}"
    payloads:
      paths:
        - - "/swagger-ui-bundle.js"

    headers:
      Accept: text/html
    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "swagger:"
          - "Swagger 2.0"
          - '"swagger":'
          - "Swagger UI"
          - "loadSwaggerUI"
          - "**token**:"
          - 'id="swagger-ui'
        condition: or

      - type: status
        status:
          - 200

    extractors:
      - type: regex
        part: body
        group: 1
        regex:
          - " @version (v[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3})"