### REQUEST
GET /status.htm HTTP/1.1
Host: 185.99.214.43
User-Agent: Mozilla/5.0
Referer: http://185.99.214.43/login.htm

### RESPONSE
HTTP/1.1 200 OK
Content-Type: text/html
Connection: close
Server: RTK Web 0.9
X-Frame-Options: SAMEORIGIN
Content-Length: 7408

<!DOCTYPE HTML><html><head>
<meta http-equiv="Pragma" content="no-cache">
<script>setTimeout(function(){top.location.reload();}, 310000);</script>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<link href="reset.css" rel="stylesheet" type="text/css" />
<link href="base.css" rel="stylesheet" type="text/css" />
<link href="style.css" rel="stylesheet" type="text/css" />
<script src="share.js" type="text/javascript" ></script>
 <title>DSL Router Status</title>
</head>
<body id="adsl" onload="onload();">
<blockquote>
<div class="intro_main ">
<table class="striped">
<tr><th>Date/Time</th><td>Sun Jan  1 7:19:50 2012</td></tr>
<tr><th>Firmware Version</th><td>ZXV-818-P/Vr.1.21</td></tr>
<tr><th>Built Date</th><td>Apr  6 2021 03:23:43</td></tr>
<tr><th>Serial Number</th><td>001AEF673134</td></tr>
</table>
<table class="striped">
<tr><th width="30%">Operational Status</th><td>ADSL2+ AnnexA</td></tr>
<tr><th>Upstream Speed</th><td>1249 kbps</td></tr>
<tr><th>Downstream Speed</th><td>10239 kbps</td></tr>
</table>
<table class="striped">
<tr><th width="30%">Inform Status</th><td>Inform no response</td></tr>
<tr><th>Connection Request Status</th><td>Connection request is broken</td></tr>
</table>
<table class="striped">
<tr><th width="30%">IP Address</th><td>192.168.1.1</td></tr>
<tr><th>Subnet Mask</th><td>255.255.255.0</td></tr>
<tr><th>IPV6 Address</th><td>fe80::21a:efff:fe67:3134</td></tr>
<tr><th>DHCP Server</th><td>Enable</td></tr>
<tr><th>MAC Address</th><td>00:1A:EF:67:31:34</td></tr>
</table>
<table class="striped">
<tr><th width="30%">DNS Mode</th><td>Manual</td></tr>
<tr><th>DNS Servers</th><td>185.174.137.240<br>8.8.8.8</td></tr>
</table>
<form action="form2WebRefresh.cgi" method=POST name="status">
<INPUT TYPE="HIDDEN" NAME="pppoenum" VALUE="" >
<INPUT TYPE="HIDDEN" NAME="connect" VALUE="" >
<table class="striped">
<tr><th>Interface</th><th>VPI/VCI</th><th>Encap</th><th>Droute</th><th>Protocol</th><th>IP Address</th><th>Gateway</th><th>Status</th></tr>
<TR><TD>pppoe1</TD><TD>0/35</TD><TD>LLC</TD><TD>Off</TD><TD>PPPoE</TD><TD>185.99.214.43</TD><TD>100.113.0.1</TD><TD>up 0 7:18:33</TD></TR>
</TABLE>
</form>
</blockquote>
</body>
</html>
