id: aws-subdomain-takeover
info:
  name: AWS S3 Bucket Subdomain Takeover
  author: MethodSecurity
  severity: high
  description: |
    This template detects subdomain takeovers on AWS S3 by checking for common error messages indicating unclaimed or unavailable buckets.
  tags: subdomain,takeover,aws,s3

requests:
  - method: GET
    path:
      - "{{BaseURL}}"
    matchers-condition: or
    matchers:
      - type: word
        words:
          - "NoSuchBucket"
          - "The specified bucket does not exist"
          - "404 Not Found"
      - type: status
        status:
          - 404
          - 403
    extractors:
      - type: regex
        regex:
          - "(NoSuchBucket|The specified bucket does not exist)"
