id: cname-subdomain-takeover
info:
  name: CNAME Subdomain Takeover Detection
  author: MethodSecurity
  severity: high
  description: |
    This template detects potential subdomain takeovers by identifying unclaimed CNAME records that point to external services.
  tags: subdomain,takeover,cname

requests:
  - method: DNS
    dnstype: CNAME
    host:
      - "{{Hostname}}"
    matchers:
      - type: word
        condition: and
        words:
          - "CNAME"
          - ".s3.amazonaws.com"
          - ".herokudns.com"
          - ".cloudapp.net"
          - ".trafficmanager.net"
          - ".storage.googleapis.com"
      - type: word
        words:
          - "NXDOMAIN"
      - type: status
        status:
          - 200
    extractors:
      - type: regex
        regex:
          - "CNAME\s+(.*)"  # Extracts the CNAME target
