package common

import (
	"testing"

	wafcommon "github.com/Method-Security/webscan/generated/go/common"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestFingerprintApplicationFirewallRejectsInfrastructureOnlySignals(t *testing.T) {
	tests := []struct {
		name       string
		body       string
		headers    map[string]string
		statusCode int
	}{
		{
			name:       "cloudflare edge headers on not found",
			headers:    map[string]string{"cf-ray": "abc-IAD", "server": "cloudflare"},
			statusCode: 404,
		},
		{
			name:       "cloudfront error response",
			body:       "The request could not be satisfied. Generated by cloudfront",
			headers:    map[string]string{"x-amz-cf-id": "request-id", "server": "CloudFront"},
			statusCode: 403,
		},
		{
			name:       "azure front door response",
			headers:    map[string]string{"x-azure-ref": "reference"},
			statusCode: 503,
		},
		{
			name:       "google trace response",
			headers:    map[string]string{"x-cloud-trace-context": "trace/span"},
			statusCode: 403,
		},
		{
			name:       "oracle diagnostic response",
			headers:    map[string]string{"x-oracle-dms-ecid": "ecid"},
			statusCode: 403,
		},
		{
			name:       "generic cloudflare error text",
			body:       "This documentation explains error code: 1000",
			statusCode: 403,
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			body := test.body
			fingerprint := FingerprintApplicationFirewall(&body, test.headers, &test.statusCode)
			assert.Nil(t, fingerprint)
		})
	}
}

func TestFingerprintApplicationFirewallAcceptsExplicitChallengeHeaders(t *testing.T) {
	tests := []struct {
		name             string
		headers          map[string]string
		statusCode       int
		expectedProvider wafcommon.WafProviderEnum
	}{
		{
			name:             "aws challenge",
			headers:          map[string]string{"X-Amzn-Waf-Action": "Challenge"},
			statusCode:       202,
			expectedProvider: wafcommon.WafProviderEnumAws,
		},
		{
			name:             "aws captcha",
			headers:          map[string]string{"x-amzn-waf-action": "captcha"},
			statusCode:       405,
			expectedProvider: wafcommon.WafProviderEnumAws,
		},
		{
			name:             "cloudflare challenge",
			headers:          map[string]string{"CF-Mitigated": "challenge"},
			statusCode:       200,
			expectedProvider: wafcommon.WafProviderEnumCloudflare,
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			fingerprint := FingerprintApplicationFirewall(nil, test.headers, &test.statusCode)
			require.NotNil(t, fingerprint)
			assert.Equal(t, test.expectedProvider, fingerprint.Provider)
		})
	}
}

func TestFingerprintApplicationFirewallRequiresExpectedHeaderValue(t *testing.T) {
	statusCode := 403

	assert.Nil(t, FingerprintApplicationFirewall(nil, map[string]string{"cf-mitigated": "redirect"}, &statusCode))
	assert.Nil(t, FingerprintApplicationFirewall(nil, map[string]string{"x-amz-waf-action": "challenge"}, &statusCode))
}

func TestFingerprintApplicationFirewallRequiresBlockStatusForBody(t *testing.T) {
	body := "Access Denied - Sucuri Website Firewall"
	okStatus := 200
	blockedStatus := 403

	assert.Nil(t, FingerprintApplicationFirewall(&body, nil, &okStatus))
	fingerprint := FingerprintApplicationFirewall(&body, nil, &blockedStatus)
	require.NotNil(t, fingerprint)
	assert.Equal(t, wafcommon.WafProviderEnumSucuri, fingerprint.Provider)
}

func TestFingerprintApplicationFirewallRejectsAmbiguousProviders(t *testing.T) {
	statusCode := 403
	headers := map[string]string{
		"x-amzn-waf-action": "challenge",
		"cf-mitigated":      "challenge",
	}

	assert.Nil(t, FingerprintApplicationFirewall(nil, headers, &statusCode))
}

func TestFingerprintApplicationFirewallReturnsFingerprintCopy(t *testing.T) {
	statusCode := 403
	headers := map[string]string{"x-amzn-waf-action": "challenge"}

	fingerprint := FingerprintApplicationFirewall(nil, headers, &statusCode)
	require.NotNil(t, fingerprint)
	fingerprint.Headers[0] = "corrupted"
	fingerprint.Body[0].Pattern = "corrupted"

	nextFingerprint := FingerprintApplicationFirewall(nil, headers, &statusCode)
	require.NotNil(t, nextFingerprint)
	assert.Equal(t, []string{"x-amzn-waf-action"}, nextFingerprint.Headers)
	assert.Equal(t, "request blocked by aws waf", nextFingerprint.Body[0].Pattern)
}

func TestDetectWafIncludesMatchedEvidence(t *testing.T) {
	statusCode := 403
	httpRequestResponse := &wafcommon.HttpRequestResponse{
		Response: &wafcommon.HttpResponse{
			StatusCode: &statusCode,
			ResponseHeaders: map[string][]string{
				"CF-Mitigated": {"", "challenge"},
			},
		},
	}

	detection := DetectWaf(httpRequestResponse)
	require.NotNil(t, detection)
	assert.Equal(t, wafcommon.WafProviderEnumCloudflare, detection.Provider)
	assert.Equal(t, []string{"cf-mitigated"}, detection.MatchedHeaders)
	assert.Empty(t, detection.MatchedBodyPatterns)
}

func TestDetectWafReturnsFingerprintCopy(t *testing.T) {
	statusCode := 403
	httpRequestResponse := &wafcommon.HttpRequestResponse{
		Response: &wafcommon.HttpResponse{
			StatusCode: &statusCode,
			ResponseHeaders: map[string][]string{
				"CF-Mitigated": {"challenge"},
			},
		},
	}

	detection := DetectWaf(httpRequestResponse)
	require.NotNil(t, detection)
	detection.Fingerprint.Headers[0] = "corrupted"
	detection.Fingerprint.Body[0].Pattern = "corrupted"
	detection.MatchedHeaders[0] = "corrupted"

	nextDetection := DetectWaf(httpRequestResponse)
	require.NotNil(t, nextDetection)
	assert.Equal(t, []string{"cf-mitigated"}, nextDetection.Fingerprint.Headers)
	assert.Equal(t, "attention required! | cloudflare", nextDetection.Fingerprint.Body[0].Pattern)
	assert.Equal(t, []string{"cf-mitigated"}, nextDetection.MatchedHeaders)
}

func TestDetectWafIncludesMatchedBodyPattern(t *testing.T) {
	statusCode := 403
	httpRequestResponse := &wafcommon.HttpRequestResponse{
		Response: &wafcommon.HttpResponse{
			StatusCode: &statusCode,
			ResponseBody: &wafcommon.Body{
				Kind: "text",
				Text: &wafcommon.TextBody{Value: "Access Denied - Sucuri Website Firewall"},
			},
		},
	}

	detection := DetectWaf(httpRequestResponse)
	require.NotNil(t, detection)
	assert.Equal(t, wafcommon.WafProviderEnumSucuri, detection.Provider)
	assert.Equal(t, []string{"access denied - sucuri website firewall"}, detection.MatchedBodyPatterns)
}

func TestDetectWafFromResponsesReturnsSingleTargetDetection(t *testing.T) {
	statusCode := 403
	responses := []*wafcommon.HttpRequestResponse{
		{
			Response: &wafcommon.HttpResponse{
				StatusCode: &statusCode,
				ResponseHeaders: map[string][]string{
					"CF-Mitigated": {"challenge"},
				},
			},
		},
		{
			Response: &wafcommon.HttpResponse{
				StatusCode: &statusCode,
				ResponseBody: &wafcommon.Body{
					Kind: "text",
					Text: &wafcommon.TextBody{Value: "Cloudflare's security service blocked this request"},
				},
			},
		},
	}

	detection := DetectWafFromResponses(responses)
	require.NotNil(t, detection)
	assert.Equal(t, wafcommon.WafProviderEnumCloudflare, detection.Provider)
	assert.Equal(t, []string{"cf-mitigated"}, detection.MatchedHeaders)
	assert.Equal(t, []string{"cloudflare's security service"}, detection.MatchedBodyPatterns)
}

func TestDetectWafFromResponsesRejectsAmbiguousTargetProviders(t *testing.T) {
	statusCode := 403
	responses := []*wafcommon.HttpRequestResponse{
		{
			Response: &wafcommon.HttpResponse{
				StatusCode: &statusCode,
				ResponseHeaders: map[string][]string{
					"CF-Mitigated": {"challenge"},
				},
			},
		},
		{
			Response: &wafcommon.HttpResponse{
				StatusCode: &statusCode,
				ResponseHeaders: map[string][]string{
					"X-Amzn-Waf-Action": {"challenge"},
				},
			},
		},
		{
			Response: &wafcommon.HttpResponse{
				StatusCode: &statusCode,
				ResponseBody: &wafcommon.Body{
					Kind: "text",
					Text: &wafcommon.TextBody{Value: "Cloudflare's security service blocked this request"},
				},
			},
		},
	}

	assert.Nil(t, DetectWafFromResponses(responses))
}
