id: umami-panel

info:
  name: Umami Panel - Detect
  author: userdehghani
  severity: info
  metadata:
    verified: true
    max-request: 1
    shodan-query: http.favicon.hash:-130447705
  tags: panel,umami,login,detect

http:
  - method: GET
    path:
      - "{{BaseURL}}/login"
      - "{{BaseURL}}/favicon.ico"

    stop-at-first-match: true
    matchers-condition: or
    matchers:
      - type: word
        part: body
        words:
          - 'Login | umami'
          - 'umami</div>'
        condition: or
        case-insensitive: true

      - type: dsl
        dsl:
          - "status_code==200 && (\"-130447705\" == mmh3(base64_py(body)))"
# digest: 4a0a004730450220172b896da3d6bd42b77029a5548cba1ea8a4852ecadc712d6e3f2a7d6b35dcfd022100886497be5d4a19d2cb6c879e61fbb41280e2c9be3e88233da54f4e621a9a4739:922c64590222798bb761d5b6d8e72950