### REQUEST
GET / HTTP/1.1
Host: 185.162.40.226
User-Agent: Mozilla/5.0

### RESPONSE
HTTP/1.1 200 OK
Content-Length: 69
Date: Sat, 13 Jun 2026 01:17:06 GMT
Server: lighttpd/1.4.29

<html><script>window.location = "/cgi-bin/login.cgi";</script></html>
