### REQUEST
GET /rest/ HTTP/1.1
Host: 188.209.153.168

### RESPONSE
HTTP/1.1 404 Not Found
Cache-Control: no-store
Connection: Keep-Alive
Content-Length: 99
Content-Type: text/html
Date: Sat, 13 Jun 2026 00:47:58 GMT
Expires: 0
Pragma: no-cache
X-Frame-Options: sameorigin

<!doctype html>
<html lang=en>
<title>Error 404 : Not Found</title>
<h1>Error 404 : Not Found</h1>
