### REQUEST
GET /rest/ HTTP/1.1
Host: 213.207.195.218

### RESPONSE
HTTP/1.1 401 Unauthorized
Cache-Control: max-age=31536000
Connection: Keep-Alive
Content-Length: 38
Content-Type: application/json
Date: Sat, 13 Jun 2026 01:15:20 GMT
Expires: Sun, 13 Jun 2027 01:15:20 GMT
WWW-Authenticate: Basic
X-Frame-Options: sameorigin

{"error":401,"message":"Unauthorized"}
