### REQUEST
GET / HTTP/1.1
Host: 5.160.162.74
User-Agent: Mozilla/5.0
Accept: */*

### RESPONSE
HTTP/1.1 200 OK
Connection: Keep-Alive
Content-Length: 7064
Content-Type: text/html
Date: Sat, 13 Jun 2026 01:16:38 GMT
Expires: 0

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="icon" href="/favicon.png"/>
<title>RouterOS router configuration page</title>
<style type="text/css">
body { font-family: Verdana, Geneva, sans-serif; font-size: 11px; }
#container { width: 700px; margin: 0 auto; }
#box { background: #ffffff; filter: progid:DXImageTransform.Microsoft.gradient(startColorstr=#ffffff,endColorstr=#f3f3f3); border: 1px solid #c1c1c1; padding: 30px; }
h1 { font-size: 14px; padding-bottom: 5px; border-bottom: 1px solid #c1c1c1; }
h2 { font-size: 12px; padding-bottom: 3px; }
table { width: 100%; }
fieldset { border: 0; }
.floater { float: left; text-align: center; width: 23%; margin: 4px 1%; padding: 5px 0; border: 1px solid #c1c1c1; }
.floater img { display: block; margin: 0 auto 5px auto; }
.label { width: 80px; }
input.btn { background: #f6921e; color: white; border: 1px solid #c1c1c1; padding: 2px 10px; cursor: pointer; }
</style>
<script>
function login(user, pwd, autologin) {
    var expires = new Date();
    expires.setTime(expires.getTime() + (30 * 24 * 60 * 60 * 1000));
    document.cookie = 'username=' + user + '; expires=' + expires.toGMTString() + '; path=/';
    window.name = (autologin ? 'autologin=' : 'login=') + user + '|' + pwd;
    window.location.replace('/webfig/' + window.location.hash);
}
function loaded() {
    document.getElementById('name').focus();
}
</script>
</head>
<body onload="loaded()">
<div id="container">
<div id="box">
<a href="http://mikrotik.com"><img src="mikrotik_logo.png" style="float: right;" /></a>
<br style="clear: both;"/>
		<h1>RouterOS v6.49.18</h1>
        <p>You have connected to a router. Administrative access only. If this device is not in your possession, please contact your local network administrator. </p>
      <table id="login">
	<tr><td colspan="3"><h2>WebFig Login:</h2>
        <tr><td class="label">Login: <td><input id="name" type="text" tabindex="1">
        <tr><td class="label">Password: <td><input id="pwd" type="password" tabindex="2">
        <tr><td><input id="login" type="button" class="btn" value="Login" tabindex="3" onclick="login(document.getElementById('name').value,document.getElementById('pwd').value,false)">
      </table>
            <fieldset>
            <div class="floater"><a href="http://www.mikrotik.com/download/winbox.exe"><img src="winbox.png"/></a><br/><label>Winbox</label></div>
            <div class="floater"><a href="telnet://5.160.162.74"><img src="telnet.png"/></a><br/><label>Telnet</label></div>
            <div class="floater"><a href="/graphs"><img src="green.png"/></a><br/><label>Graphs</label></div>
            <div class="floater"><a href="/help/license.html"><img src="license.png"/></a><br/><label>License</label></div>
            </fieldset>
            <div style="float: right">&copy; mikrotik</div>
    </div>
</div>
</div>
</body>
</html>
