imports:
  graphql: ./graphql.yml
types:
  SecuritySchemeName: string
  SecurityScheme:
    properties:
      type: string        # Can be 'basic', 'apiKey', 'http', 'oauth2', 'openIdConnect', 'mutualTLS'
      description: optional<string>
      name: optional<SecuritySchemeName>  # For apiKey
      in: optional<string>    # Can be 'query', 'header', or 'cookie' for apiKey
      scheme: optional<string>  # For http, e.g., 'bearer', 'basic'
      bearerFormat: optional<string>  # For http with scheme 'bearer'
      flow: optional<string>  # For oauth2 v2
      authorizationUrl: optional<string>  # For oauth2 v2
      tokenUrl: optional<string>  # For oauth2 v2
      scopes: optional<map<string, string>>  # For oauth2 v2
      flows: optional<OAuthFlows>  # For oauth2 v3
      openIdConnectUrl: optional<string>  # For openIdConnect
  OAuthFlows:
    properties:
      implicit: optional<OAuthFlow>
      password: optional<OAuthFlow>
      clientCredentials: optional<OAuthFlow>
      authorizationCode: optional<OAuthFlow>
  OAuthFlow:
    properties:
      authorizationUrl: optional<string>
      tokenUrl: optional<string>
      refreshUrl: optional<string>
      scopes: optional<map<string, string>>
  SecurityRequirement:
    properties:
      schemes: map<string, list<string>>  # Map of security scheme names to required scopes or empty list
  Route:
    properties:
      path: string
      queryParams: optional<list<string>>
      security: optional<SecurityRequirement>  # Replaced with SecurityRequirement for detailed auth handling
      method: string
      type: APIType
      description: string
  RoutesReport:
    properties:
      target: string
      appType: APIType
      baseEndpointUrl: string
      version: optional<string>
      schemaUrl: optional<string>
      routes: list<Route>
      securitySchemes: optional<map<SecuritySchemeName, SecurityScheme>>  # New: Contains security schemes defined at the app level
      security: optional<list<SecurityRequirement>>  # New: Security at the app level
      queries: optional<list<graphql.GraphQLQuery>>
      raw: string
      errors: optional<list<string>>
  APIType:
    enum:
      - Grpc
      - GraphQL
      - SwaggerV2
      - SwaggerV3